const express = require('express');
const router = express.Router();
const authController = require('../controllers/authController');
const authMiddleware = require('../middleware/authMiddleware');
//router.post("/create-post",authMiddleware,postController.createPost);
router.post('/register-v1', authController.register);
router.post('/send-otp-v1', authController.sendOTP);
router.post('/verify-otp-v1', authController.verifyOTP);
router.post('/login-v1', authController.login);
router.post('/logout-v1', authMiddleware, authController.logout);
module.exports = router;